#
# GreenCity BackUser Service
#
apiVersion: v1
kind: Service
metadata:
  name: backuser
  namespace: greencity
  labels:
    app: backuser
    component: backend
spec:
  type: ClusterIP
  selector:
    app: backuser
  ports:
    - name: http
      port: 8060
      targetPort: 8060
      protocol: TCP
