# GreenCity Ansible Inventory
---
all:
  children:
    greencity:
      hosts:
        greencity-vm:
          ansible_host: 192.168.10.20
          ansible_user: vagrant
          ansible_ssh_private_key_file: ../vagrant/.vagrant/machines/greencity-vm/virtualbox/private_key
          ansible_python_interpreter: /usr/bin/python3
